### ISSUE TITLE
我香槟金B1博通cpu的k2p能用吗

### ISSUE THREAD

**Issue by cwcwcw721** [felix-fly/v2ray-padavan#1]
之前刷了玉石工作室的1.1梅林，但是面板不支持v2ray

**Comment by felix-fly** [comment]
博通的不能刷padavan，因为v2ray体积大，k2p内存小，所以一般的固件都不会包含，梅林的理论上有足够的内存空间的话应该可以自己安装配置v2ray

**Comment by cwcwcw721** [comment]
谢谢回复，我的梅林版本好像是比较低。如果自己安装配置v2ray是不是要通过ssh什么的去搞？
![image](https://user-images.githubusercontent.com/11497111/52764526-8c914a80-305b-11e9-93ce-4b2a6ab5c6d1.png)

**Comment by felix-fly** [comment]
是的，最重要的是先确认有足够的内存空间，目前最新版的v2ray压缩过后已经4mb多了

**Comment by cwcwcw721** [comment]
我记得是128M的吧。平常空闲一半内存这样。60M左右，这样够吗

**Comment by felix-fly** [comment]
这个是运存，内存相对于电脑硬盘的大小，k2p是16mb，一般固件大小在4～15mb之间，固件包含软件越多体积越大，剩下的自由空间就越少。

说到运存，可以有另外一种解决方案，路由启动时执行脚本，然后在脚本中将v2ray通过网络加载到运存当中来运行，之前曾经看到过有人发过相关的文章，内存不够可以试试这种方式。

**Comment by cwcwcw721** [comment]
我就看到官方参数写着内存128MB没看到，只是在网上搜的都是A1，A2的固件我看他们刷的官改，也可以玩v2ray，他们都能装的下。但是博通cpu的作者好像没有更新了。还是感谢。
![image](https://user-images.githubusercontent.com/11497111/52774742-ee13e200-3078-11e9-9fb5-7506c5ef0047.png)

**Comment by ntgeralt** [comment]
电脑或手机，内存多数指memory，易失性的RAM
