### ISSUE TITLE
如果停止v2ray服务，怎么删除透明代理（iptables.sh）

### ISSUE THREAD

**Issue by jyoryo** [felix-fly/v2ray-padavan#6]
你好，我是安装在路由器中，使用该方式翻墙都正常，但是有时想停止V2ray，不知道设置的透明代理（iptables.sh）该如何删掉？
谢谢！

**Comment by felix-fly** [comment]
防火墙脚本规则注释掉这个应该就可以了

**Comment by jyoryo** [comment]
可能上面没有描述清楚。
停止运行v2ray,由于iptables.sh设置的规则已经添加，我想在停止v2ray的同时，也将原来添加的iptables.sh的规则删掉或停掉。

防火墙脚本规则注释掉，意思是再运行这个脚本，不过脚本内容都注释掉？那这个就成了空脚本。

**Comment by felix-fly** [comment]
不用修改iptables.sh文件，我的意思是注释这个：
> 高级设置 -> 自定义设置 -> 脚本 -> 在防火墙规则启动后执行:
> #/etc/storage/v2ray/iptables.sh

保存后防火墙应该会重启，之前的规则就没有了，你测试下，我记得是这样的

**Comment by jyoryo** [comment]
好的，我试下。非常感谢！

**Comment by jyoryo** [comment]
昨晚测试了，终于搞定。多谢提供思路，
具体操作为：
在v2ray停止的脚本，加上
restart_firewall
进行重启防火墙；
另外iptables.sh脚本中只有检测到v2ray在运行才添加iptable规则。
